version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./api-swihla/tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: 
      context: ./api-swihla
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./api-swihla:/myapp
      - railsgems:/usr/local/bundle
    ports:
      - "3040:3000"
    depends_on:
      - db
  client:
    build:
      context: ./front-swihla
      dockerfile: Dockerfile
    command: npm start
    volumes:
      - ./front-swihla:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - web
    ports:
      - "3050:3000"
  postgresql_pgadmin:
    image: dpage/pgadmin4
    restart: always
    labels:
      name: "db-pgadmin"
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 8088:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    # tty: true
volumes:
  railsgems:
  pgadmin-data: